Update project to GDI spec version 1.1.0
signalfx/splunk-otel-java pull request #518
Opened 2021-11-03 13:40 UTC by mateuszrzeszutek

Turns out it was just the max attribute value length, we already had implemented everything else that was introduced in 1.1.0.

2021-11-03 16:33 UTC, breedx-splk requested changes
Small naming ask.

2021-11-03 16:33 UTC, breedx-splk commented on custom/src/main/java/com/splunk/opentelemetry/SplunkTracerProviderConfigurer.java
> +  static final int SPLUNK_DEFAULT_ATTRIBUTE_VALUE_LENGTH = 12_000;
```suggestion
  static final int SPLUNK_MAX_ATTRIBUTE_VALUE_LENGTH = 12_000;
```

2021-11-04 08:59 UTC, theletterf approved these changes

2021-11-04 11:23 UTC, mateuszrzeszutek commented on custom/src/main/java/com/splunk/opentelemetry/SplunkTracerProviderConfigurer.java
> +  static final int SPLUNK_DEFAULT_ATTRIBUTE_VALUE_LENGTH = 12_000;
👍 
Done

2021-11-04 16:44 UTC, breedx-splk approved these changes

2021-11-04 16:46 UTC, merged