v1.7.0 post release changes
signalfx/splunk-otel-java pull request #633
Opened 2022-01-17 17:30 UTC by mateuszrzeszutek

2022-01-17 17:42 UTC, theletterf requested changes

2022-01-17 17:42 UTC, theletterf commented on README.md
> +The documentation below refers to the in development version of this package. Docs for the latest version ([v1.7.0](https://github.com/signalfx/splunk-otel-java/releases/latest)) can be found [here](
```suggestion
The following documentation refers to the in-development version of `splunk-otel-java`. Docs for the latest version ([v1.7.0](https://github.com/signalfx/splunk-otel-java/releases/latest)) can be found [here](https://github.com/signalfx/splunk-otel-java/blob/v1.7.0/README.md).
```

2022-01-17 17:42 UTC, theletterf commented on README.md
> +We publish [bleeding edge snapshot builds](https://oss.sonatype.org/content/repositories/snapshots/com/splunk/splunk-otel-javaagent/1.8.0-SNAPSHOT/)
```suggestion
We publish [snapshot builds](https://oss.sonatype.org/content/repositories/snapshots/com/splunk/splunk-otel-javaagent/1.8.0-SNAPSHOT/)
```

I like the colorful expression, but we can do without in docs. :P

2022-01-18 10:02 UTC, theletterf approved these changes

2022-01-19 10:22 UTC, laurit approved these changes

2022-01-19 11:01 UTC, merged