Remove host.name resource attribute
signalfx/splunk-otel-java pull request #648
Opened 2022-01-27 12:32 UTC by mateuszrzeszutek

The `host.name` attribute was incorrectly detected in cloud environments (AWS, Azure, ...) so as a quick fix it was decided to just remove it.

2022-01-27 13:19 UTC, laurit approved these changes

2022-01-27 13:55 UTC, iNikem requested changes
`host.name` (together with `host.id`) are important attributes for our internal usage telemetry. If `host.name` is correctly detected in non-cloud environments, then we should not just always remove it.

2022-01-27 14:01 UTC, mateuszrzeszutek commented
The problem is, how can we reliably detect a cloud environment?

2022-02-01 08:41 UTC, mateuszrzeszutek commented
Not needed after all

2022-02-01 08:41 UTC, closed without merging