Convert micrometer jvm metrics to otel
signalfx/splunk-otel-java pull request #804
Opened 2022-06-01 09:33 UTC by laurit

2022-06-04 00:04 UTC, breedx-splk requested changes
This seems fine. About halfway thru I realized that much of what I was reviewing was copypasta, so I stopped giving it too much scrutiny. I have a couple of questions that we should probably answer amongst our team:

* Do we expect to own this code, in our repo, long term? If not, what's the plan?
* Should we bring over corresponding tests so that refactoring can be done safely?

2022-06-04 10:46 UTC, laurit commented on buildSrc/src/main/kotlin/splunk.spotless-conventions.gradle.kts
> +    licenseHeaderFile(rootProject.file("gradle/spotless.license.java"), "(package|import|public|// Includes work from:)")
Yes, this is here because we are going to use micrometer code. Upstream use the same pattern.

2022-06-04 10:47 UTC, laurit commented on instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
> +      if (useMicrometerMetrics) {
These are to be handled in a separate PR which is blocked by your renaming PR.

2022-06-04 10:49 UTC, laurit commented on instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelJvmGcMetrics.java
> +  private boolean isGenerationalGcConfigured() {
This class is a copy from micrometer with minimal changes. If you believe that we should do bigger changes to it feel free to add a story to JIRA.

2022-06-04 10:49 UTC, laurit commented on instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelJvmGcMetrics.java
> +  private final boolean isGenerationalGc = isGenerationalGcConfigured();
This class is a copy from micrometer with minimal changes. If you believe that we should do bigger changes to it feel free to add a story to JIRA.

2022-06-04 10:49 UTC, laurit commented on instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelJvmGcMetrics.java
> +    if (!this.managementExtensionsPresent) {
This class is a copy from micrometer with minimal changes. If you believe that we should do bigger changes to it feel free to add a story to JIRA.

2022-06-04 10:51 UTC, laurit commented on instrumentation/jvm-metrics/src/test/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsTest.java
> +    // thread metrics
These align with the test for micrometer metrics, they just verify that something was reported from each of the classes.

2022-06-04 16:46 UTC, laurit commented on instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelJvmGcMetrics.java
> +  private boolean isGenerationalGcConfigured() {
I added a story for polishing metrics copied from micrometer. We can decide whether or how much we want to decide the copied code when @mateuszrzeszutek gets back.

2022-06-07 23:14 UTC, breedx-splk approved these changes
I guess we're just doing this for now.

2022-06-08 07:50 UTC, merged