Update logback and slf api
signalfx/splunk-otel-java pull request #890
Opened 2022-08-29 21:32 UTC by breedx-splk

Going to see if this work better than #888. It looks like, according to [the docs](https://www.slf4j.org/codes.html#StaticLoggerBinder), 

> Backends such as logback 1.3 and later which target slf4j-api 2.x, do not ship with org.slf4j.impl.StaticLoggerBinder. If you place a logging backend which targets slf4j-api 2.0.x, you need slf4j-api-2.x.jar on the classpath.

So I think adding slf-api 2.0.0 into the test runtime classpath should help.

2022-08-30 06:31 UTC, mateuszrzeszutek approved these changes

2022-08-30 06:32 UTC, mateuszrzeszutek commented
That reminds me, I've an open PR updating the slf4j-api in the upstream...

2022-08-30 12:12 UTC, mateuszrzeszutek requested changes
Hold on with this change:
```
java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Looks like we might have to stay on slf4j 1.x for the time being

2022-09-12 22:12 UTC, breedx-splk commented
Should we just close this now then?

2022-09-13 08:56 UTC, mateuszrzeszutek commented
Yeah, let's close it for now -- the upstream `testing-common` package does not use slf4j 2 either.

2022-09-13 08:56 UTC, closed without merging